config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new #render the form
    @task = Task.new
  end

  def create
    @task = Task.new(task_params) #more secure than above with a hash

    if @task.save
      redirect_to @task
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def task_params
      params.require(:task).permit(:title, :details)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
 <div class="form">
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :details %><br>
      <%= form.text_area :details %><br>
    </div>

    <div>
      <%= form.submit %>
    </div>
 </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<% @tasks.each do |task| %>
    <input type="checkbox" id="cbox1" value ="first_checkbox"><label for="cbox1"><%= task["title"] %></label>
<% end %>

app/views/tasks/new.html.erb
<h1 class="new-task">New Tasks</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>

<ul>
  <li><%= link_to "Edit", edit_task_path(@task) %></li>
  <li><%= link_to "Destroy", task_path(@task), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Tasks</h2>